### ISSUE TITLE
No way to pass billing address country fields in latest version

### ISSUE THREAD

**Issue by sullman** [braintree/braintree-encryption.js#25]
Sorry for posting this here, but I gather there's no better place for issues in the latest version of the library?

In the latest version of the library, the `extractValues` function looks something like this:

```
r.prototype.extractValues = function(t, e) {
                e = e || {};
                var n, i, r = t.children;
                for (i = 0; i < r.length; i++)
                    if (n = r[i], 1 === n.nodeType && n.attributes["data-braintree-name"]) {
                        var o = n.getAttribute("data-braintree-name");
                        "postal_code" === o ? e.billingAddress = {
                            postalCode: n.value
                        } : e[o] = n.value, this.scrubAttributes(n)
                    } else n.children && n.children.length > 0 && this.extractValues(n, e);
                return e
            }
```

There's some special handling to turn `postal_code` into a field within `billingAddress`, but there's no similar support for the rest of the billing address fields. In particular, there's no way to pass the country. Since AVS rules are ignored when a country other than the US is provided, the ability to provide a country is especially important. (I suspect the same could be said for the street address, but I'm selfishly concerned about the country. :] )

**Comment by EvanHahn** [comment]
Looks like we can close this 2-year-old issue!

If this is still a problem, please reach out to our support team at support@braintreepayments.com.
